### PR TITLE
upgrade dependencies, start to refactor and account for newer coffee-script compilation

### PR DESCRIPTION
**Pull request by davemo**
👋 Hey @jasonkarns and @searls, I took a stab at this today

To test, I did the following:

1. cloned https://github.com/davemo/blog.davemo.com which uses `lineman-blog`
2. symlinked global and local `lineman` to `upgrade-lineman-deps` (https://github.com/linemanjs/lineman/pull/396)
3. symlinked `lineman-blog -> grunt-markdown-blog` to my fork with these changes
4. I also ran `npm test` against these changes and made a few changes to swap `sandboxed-module` for `testdouble` (although I think there's still some gross stuff here).

There's one blocker I'm hitting that I'd love some help with if either of you have time 🤓 

The `Page` and `Post` inheritance structure was predicated on the older coffee-script syntactic sugar around ES5 constructor functions and prototype chains. I've unwound a bit of this in `5fe1edf`, but there's still something funny going on that manifests in the `archive` task:

```shell
Running "markdown:dev" (markdown) task
Pages skipped: no page sources found
Writing 10210 characters to generated/posts/2007-01-01-bundle-links.html
Writing 4730 characters to generated/posts/2008-08-18-work-bliss.html
...
Writing 5826 characters to generated/posts/2014-04-03-the-magnetic-core-philosophy.html
Writing 5826 characters to generated/index.html
Warning: app/templates/archive.pug:10
    8|         - _(site.posts).chain().clone().reverse().each(function(post){
    9|           li
  > 10|             a(href=`/${post.htmlPath()}`) #{post.title()}
    11|         - })
    12| 

post.htmlPath is not a function Used --force, continuing.
```

I'm down to pair up some time either of you are free :)

### CODE REVIEW

**Comment by davemo** [comment]
Ok, so I've got a fix for this last issue ready to go but I'm no longer able to push to this repo 😢 

Any chance we could move this repo from `testdouble/grunt-markdown-blog` to `linemanjs/grunt-markdown-blog` org so I can continue to push fixes @searls @jasonkarns ? 🤓

**Comment by davemo** [comment]
Thanks! I've got one test to fix and then I think this should be good to merge and cut a release. 🤞

**Comment by searls** [comment]
@davemo you have release rights - let it ride

**Comment by davemo** [comment]
Ok, I've kicked the tires on this sufficiently over the last couple days while working on updates to my own blog that uses `lineman-blog -> grunt-markdown-blog`. Gonna merge and draft up some release notes! 🎉

**Pull request merged**
